### ISSUE TITLE
Bold font-weight is difficult to distinguish from normal formatting

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#62] opened 2017-06-08 00:57 UTC
Formatting for Business Guide pages (possibly others) isn't Rendering

**Comment by quarterback** [comment] 2017-06-08 01:54
What formatting isn't rendering? Is this on mobile?

**Comment by rbdietz** [comment] 2017-06-08 14:39
I'm in Chrome/Mac

This page isn't rendering bold and other formatting present in the editor.

https://bloomington.in.gov/alpha/business/start/physical





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by inghamn** [comment] 2017-06-08 15:52
I've looked at it in Firefox and Chrome, and the formatting is working in my browsers.  Can any other Mac people reproduce?

**Comment by charlesbrandt** [comment] 2017-06-08 20:00
The formatting is there, but it is faint. We may want to review this after launch, but I'm hoping for now it is good enough.

**Comment by rbdietz** [comment] 2017-06-08 20:16
bold/em isn't showing up as bold/em in chrome/mac.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by inghamn** [comment] 2018-03-12 15:44
I think the bold CSS has been taken care of long ago.  We can close this out one we have confirmation that it works in each of the browsers.
- [ ] Safari / Mac
- [ ] Chrome / Mac
- [ ]  Firefox / Mac
- [ ] Firefox / Windows
- [ ] Chrome / Windows
- [ ] Edge / Windows

**Comment by charlesbrandt** [comment] 2018-03-15 18:20
Like I said earlier in the thread, the bold / strong tags are in place. The browsers are rendering them as they're specified. However, they still look faint. I believe that is what Rick is referring to. I think the problem is in what we've chosen in the CSS to represent strong / bold. This is a front-end issue. 

By default, Roboto normal doesn't look all that much different from bold or bolder. We could set a different color for bold / bolder so it stands out a bit more. For example, looking at the [business guide](https://bloomington.in.gov/business/start/physical):

<img width="777" alt="screen shot 2018-03-15 at 2 09 35 pm" src="https://user-images.githubusercontent.com/2225624/37482851-adefbd28-285b-11e8-93a2-748afcc00879.png">

I've lightened the body text slightly (#333333) and then made the first strong font-weight: bolder and color: #000000 (for the first one only). The second one does not have that. Does that make the bold stand out sufficiently?

**Comment by rbdietz** [comment] 2018-03-20 16:11
Seems to only be a problem in macOS/Chrome.

**Comment by adabutch** [comment] 2018-07-27 12:30
@charlesbrandt / @rbdietz - via commit [e05ac81](https://github.com/City-of-Bloomington/drupal-theme-cob/commit/e05ac81c0fc8b251fa0c51251ac276fa23402c91) above, check `b/strong` on this page now:

https://rogue.bloomington.in.gov/drupal/business/start/physical

**Comment by charlesbrandt** [comment] 2018-07-27 13:00
This looks more distinct to me now. I could see making the font colors different between normal and strong text -- making strong text even darker. Otherwise looks good!

**Comment by adabutch** [comment] 2018-07-27 13:08
@charlesbrandt thanks!

I've made b/strong explicitly black, should be even a little more strong appearing now.

**Comment by adabutch** [comment] 2018-07-30 19:10
closing this as going any more dark (currently is now set to black) and/or bold would need a font that supports a heavier weight.

**Closed by adabutch** 2018-07-30 19:10 UTC
Labels: front-end

**Comment by inghamn** [comment] 2026-02-12 21:24
See #284
