### ISSUE TITLE
CTAs don't appear green on basic page

### ISSUE THREAD

**Issue by quarterback** [City-of-Bloomington/drupal-theme-cob#20] opened 2017-05-20 16:40 UTC
Added a CTA to a basic page (https://bloomington.in.gov/alpha/farmers-market/salsa-contest) and it doesn't show up as a green button, just a link.

**Comment by schnippy** [comment] 2017-05-22 14:00
This should be resolved by updates made in #15.

**Comment by charlesbrandt** [comment] 2017-05-31 22:03
dupe of #15

**Closed by charlesbrandt** 2017-05-31 22:03 UTC
