### ISSUE TITLE
News Release Formatting

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#63] opened 2017-06-08 01:08 UTC
This 3-column approach doesn't work.

https://bloomington.in.gov/alpha/news/2017/05/25/756

Can we wrap the body text around the image so the text isn't in one super long column?

**Comment by rbdietz** [comment] 2017-06-08 17:27
2-column is fine.  It just doesn't work when there is 3 columns.

**Comment by adabutch** [comment] 2018-07-27 19:49
closing this issue out as it's more or less a duplicate of #109 ... generally easier to follow along in a single ticket, feel free to reopen if need be.

**Closed by adabutch** 2018-07-27 19:49 UTC
